- hosts: localhost
  become: true
  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: true
      tags:
        - asdf
        - zsh
  tasks:
    - import_tasks: tasks/zsh.yml
    - import_tasks: tasks/asdf.yml

