- hosts: localhost
  become: true
  vars_files:
    - vars/asdf.yml
  pre_tasks:
    - name: Update apt cache
      apt:
        update_cache: true
      tags:
        - asdf
        - asdf-tools
        - core
        - zsh
  tasks:
    - import_tasks: tasks/core.yml
    - import_tasks: tasks/zsh.yml
    - import_tasks: tasks/asdf.yml
