- name: Install asdf tool version manager
  git:
    repo: 'https://github.com/asdf-vm/asdf.git' 
    version: 'v0.13.1'
    dest: '~/.asdf'
  tags:
    - asdf

- name: Add asdf to oh-my-zsh plugins list
  replace:
    path: ~/.zshrc
    regexp: 'plugins=\((.*)\)'
    replace: 'plugins=(asdf \1)'
  tags:
    - asdf

- name: Install asdf golang plugin
  shell: '{{ asdf_executable }} plugin add golang'
  tags:
    - asdf

- name: Install asdf neovim plugin
  shell: '{{ asdf_executable }} plugin add neovim'
  tags:
    - asdf

- name: Install asdf python plugin
  shell: '{{ asdf_executable }} plugin add python'
  tags:
    - asdf

- name: Install asdf rust plugin
  shell: '{{ asdf_executable }} plugin add rust'
  tags:
    - asdf

- name: Install asdf tool versions
  shell: '{{ asdf_executable }} install'
  tags:
    - asdf-tools

- name: Set asdf tool versions globally
  copy:
    src: .tool-versions
    dest: ~/
  tags:
    - asdf-tools
