- name: Install system packages
  apt:
    pkg: 
      - build-essential 
      - curl 
      - libbz2-dev 
      - libffi-dev 
      - liblzma-dev 
      - libncursesw5-dev 
      - libreadline-dev 
      - libsqlite3-dev 
      - libssl-dev 
      - libxml2-dev 
      - libxmlsec1-dev 
      - llvm 
      - make 
      - tk-dev 
      - unzip
      - wget 
      - xz-utils 
      - zlib1g-dev 
  tags:
    - core
