- name: Install zsh
  apt: name=zsh
  tags:
    - zsh

- name: Install oh-my-zsh
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  tags:
    - zsh

- name: Install zsh-autosuggestions plugin
  git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions' 
    dest: '~/.oh-my-zsh/plugins/zsh-autosuggestions'
  tags:
    - zsh

- name: Add zsh-autosuggestions to oh-my-zsh plugins list
  replace:
    path: ~/.zshrc
    regexp: 'plugins=\((.*)\)'
    replace: 'plugins=(\1 zsh-autosuggestions)'
  tags:
    - zsh
